### ISSUE TITLE
Obtain RHEL and SLES CI resources

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/ci#129]
Moving the discussion from https://github.com/kata-containers/tests/pull/1263#issuecomment-472050392 to it's own (open! ;) issue.

> @egernst, @gnawux, @ttx - could you clarify any of this? Specifically:
> 
> Do we have (or can we get) RHEL+SLES licenses?
> If not, do we have a way to fund the PAYG option (2) @chavafg mentioned above?

- RHEL != CentOS and RHEL != Fedora
- SLES != openSUSE

We build packages for these distros using OBS:

- https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/

... so please can we investigate obtainining CI resources for both these distros.

Related:

- https://github.com/kata-containers/documentation/pull/397
- https://github.com/kata-containers/ci/issues/3
- https://github.com/kata-containers/ci/issues/126

**Comment by ttx** [comment]
We do not currently have RHEL or SLES licenses. If RHEL/SLES testing is needed, and our current arrangement with those cloud providers do not include SLES/RHEL PAYG access, we should probably engage with Suse and Red Hat see if they would be willing to donate licenses so that we can do proper validation testing. We can engage at a higher level, but it's probably best to engage with Kata developers from those companies first, see if they can pull the required strings...

FWIW for OpenStack we do run tests on CentOS and OpenSUSE Leap to cover for RHEL and SLES. Last we engaged with Suse to get SLES licenses they told us using OpenSUSE Leap would be virtually identical to testing on SLES... Can you explain how RHEL != CentOS and SLES != openSUSE Leap for Kata validation testing, beyond the lack of support services ?

**Comment by ttx** [comment]
For reference, here is last time we had the SLES discussion and concluded OpenSUSE Leap would be enough: https://github.com/kata-containers/ci/issues/5#issuecomment-453529980

**Comment by jodh-intel** [comment]
Great - I'd forgotten that thread, so sounds like SLES is covered. However, I know we've seen (and been bitten by) differences between CentOS and RHEL so that one would be worth adding to the CI imho.

The issues we've seen include certain packages being unavailable in the default set of RHEL repos. However, enabling the required repo(s) required additional licenses I think? @GabyCT - can you recall the details / point at the issue/PRs where we had RHEL issues?

**Comment by GabyCT** [comment]
@jodh-intel from what I remember you need a license to RHEL because you need to enable repositories which will valid your license in order to download general packages like docker, etc.

**Comment by ttx** [comment]
OK... Is there any Red Hat developer involved with Kata yet that we could ping for resources ? Otherwise I'll ask other contacts I have there.

**Comment by jodh-intel** [comment]
Hi @ttx - I think @lsm5, @fatherlinux and @mrguitar are either involved, or soon to be.

**Comment by ttx** [comment]
@lsm5, @fatherlinux, @mrguitar : what's your take on the difference between CentOS and RHEL as far as validation goes ? Is there a mechanism through which we can get RHEL licenses to be used for software validation purposes ? These should only be needed until RHEL properly includes Kata containers in the distro :)

**Comment by grahamwhaley** [comment]
Also /cc @stefanha @dagrh

**Comment by dagrh** [comment]
OK, I'll mail a few people and see where we get to!

**Comment by dagrh** [comment]
It was suggested that you try, the RH developer subscription:

https://developers.redhat.com/products/rhel/download/

that should get you a RHEL7.6 OK I think; note that the qemu in there will be the 'stable' (1.5.3) version; so it's best for testing NEMU/upstream qemu rather than the shipped qemu.

**Comment by ttx** [comment]
We actually want to run RHEL on a public cloud provider (Azure) under a "Bring your own subscription" model. So I suspect we don't really need access to the software, as much as we need a proper subscription to point Azure at ?

**Comment by jodh-intel** [comment]
I think we a "full" subscripto to RHEL too since the dev version doesn't have access to some of the standard RHEL repos from what @GabyCT found recently I think?

**Comment by dagrh** [comment]
Hmm, so the 'docker' packages should be in the 'extras' channel; which hmm I'm expecting that Developer set can get to; let me check.

**Comment by dagrh** [comment]
ttx: I tried going through the registration at https://developers.redhat.com/  and registered as a dev using a separate email, and the account it created had a subscription which worked just as normal with the RHEL subscription-manager - so I think you should be able to poke that into the same box in Azure;  if not then please tell me exactly what that Azure is asking for.
(I can see under https://access.redhat.com/management/subscriptions  it's showing me a subscription number and SKU etc)

@GabyCT For docker you need to enable the 'extras' repo, the following magic worked for me:

  subscription-manager repos --enable=rhel-7-server-extras-rpms
  yum update
(again that's on a developer subscription)

**Comment by ttx** [comment]
Thanks @dagrh ! @chavafg has experience with the Azure Portal and might be able to tell us if that would work...

**Comment by GabyCT** [comment]
@ttx and @dagrh , sorry for the late response but until today I had the opportunity to check this. I was able to run a RHEL image in azure (7.6) (it says `pay as you go` and `Pricing not available for this offering` when creating the image). I do not have to installed any other license to get the packages. However, I found that some packages are not available like `haveged, jq, smem, chronic, yamllint, etc..` this will limit us the amount of tests that we can run and I also noticed that the docker version that is supported is 13.01 so I enabled the centos repository for docker in order to retrieve our current supported version which is 18.06 (honestly, I do not know if that is the best workaround) but no other issues, I have found using the azure image like it is.

**Comment by dagrh** [comment]
Hi @GabyCT It looks like haveged and jq are in the 'epel' repository (a less maintained repo of stuff from Fedora) see the instructions at: https://fedoraproject.org/wiki/EPEL?rd=EPEL/en
I think the docker 1.13.1 is the latest version we have packaged in RHEL.

**Comment by GabyCT** [comment]
The CI on RHEL is failing https://github.com/kata-containers/ci/issues/139

**Comment by GabyCT** [comment]
RHEL ci issue was solved with https://github.com/kata-containers/tests/pull/1380
