### ISSUE TITLE
ci: Arm job queues getting large

### ISSUE THREAD

**Issue by chavafg** [kata-containers/ci#159]
Hi, 

Now that the arm job is very stable and we have added additional jobs for testing every repo, we have seen that some arm jobs are getting in queue for some hours. 
I was wondering how feasible would be to be able to have one other node to decrease the time that PRs wait for being tested?

Thanks 
/cc @Pennyzct @egernst

**Comment by Pennyzct** [comment]
Hi~ @chavafg thanks for the proposal. 
I will talk around internally to discuss the possibilities of add more ARM nodes on Kata Project. 
I was just talking about with @grahamwhaley in [agent#545](https://github.com/kata-containers/agent/pull/545) to bring ARM CI online on agent repo, it may bring more workload.
so, i will update you asap about adding more ARM nodes here. ;)

**Comment by chavafg** [comment]
Thank you @Pennyzct

**Comment by grahamwhaley** [comment]
for ref, I was doing a little head-math-back-of-envelope yesterday, thinking briefly about the single node CIs we have....
We land about 50+ PRs a week across the project, so about 10 per working weekday.
Each PR shall we say might consume two CI runs (one pre-review, one post-review).
Each CI run takes 1-2h (shall we avg 1.5h?)
So, right now, we are maybe hitting (10*2*1.5) ~30h of CI runtime per day.. and, well, we only have 24h in each day :-) 
Obviously, we are not quite that bad right now, or we'd have a permanent queue building up on the single node CIs (that is afaik today, ARM, s390, Power8 and metrics). But, the CIs normally get slower over time (as we add more tests), and the project gets busier over time (as we get more contributors etc.)...

It may be that soon a single node CI will not be able to cope. Just a heads up...

**Comment by jodh-intel** [comment]
Reading this plus https://github.com/kata-containers/tests/issues/1556 makes me wonder... Do all architectures CI's take approximately the same amount of time to run? If they do, stop reading now :smile:

**Iff**, for example, the main Jenkins system (`x86_64`) is significantly quicker (possibly simply due to more nodes) than the other architectures CI systems, maybe we could consider introducing a slightly altered CI process:

- `/test` will trigger tests on `x86_64` only.
- `/test-${arch}` will do the obvious thing.
- `/test-all` will also do the obvious thing.

We would still mandate that all CI's on all architectures pass before a PR can land, but we'd do a "sniff test" on the fastest CI environment as a "pre-test". If that pre-test fails, there is little point running on all the other architectures CI's until it passes the pre-test.

That approach might reduce the burden on some of the slower systems if we start to see jobs "backing up"

**Comment by grahamwhaley** [comment]
Just going to grab a few numbers off the jenkins master then:
- ARM runtime PR took 1h29
- Power8 proxy PR took 1h6
- S390 proxy PR took 1h38
- x86 runtime PR took 1h35
- metrics (x86) runtime PR took 0h15

(btw, @chavafg @alicefr @tuan-hoang1 - I think I see the s390 jenkins jobs also tracking master branch merges ... is that on purpose?)

**Comment by grahamwhaley** [comment]
btw, @Pennyzct - I'm not clear on who/how the ARM CI nodes are sponsored - but, if they are (or are not) through the ARM/Packet [works on ARM](https://www.worksonarm.com/) https://github.com/WorksOnArm/cluster - then, if you need and have not already, we can put you in touch with some of the Packet folks who might be able to help etc.

**Comment by jodh-intel** [comment]
@grahamwhaley - Thanks! Since all the figures are very similar, there doesn't seem much point in pursuing my idea... unless `/test` triggers only the metrics test? But that feels slightly odd to me. Maybe if we do eventually get pipelines, we could make `/test` trigger "unit tests + metrics" for our "sniff test"? If and only if we get good results back from those two categories do we consider running the full CI on all architectures?

**Comment by Pennyzct** [comment]
Hi~ @jodh-intel  i think the "sniff test" is quite brilliant. ;) Let the fastest machine do the quickest trial.
For now, AArch64 only do the docker integration tests, and I'm going to adding K8s, that's quite a workload. 
@grahamwhaley I have already send the request to marketing team, and i also want to not just add more ARM nodes, but also replace the existing one(quite old) with the new generation.

**Comment by Pennyzct** [comment]
@kalyxin02

**Comment by grahamwhaley** [comment]
Sniff test idea I think could be useful.
It is probably not just about build time (and, note, the metrics is only really faster as it does not run any of the QA CI tests, and only a small subset of metrics tests). We need to consider job queue length as well.
x86 has by far the most resource. I think maybe we are not even utilising all the resource we have available for x86 right now. We could maybe set up a 'quick first pass CI job' that runs the minimum QA CI checks, and have that job scheduled onto some currently spare resource (if we do have some). That might mean we can get a fast first pass smoke test on a not-too-backlogged x86 system, and then if that works, we can fire off the more comprehensive CI jobs. In theory we can probably even get Jenkins to do that automatically by chaining the smoke test as the pre-check for the main jobs....

We need to discuss with @chavafg though ;-)

**Comment by jodh-intel** [comment]
Yep. I minimum check would need to include unit tests, but also the static checks (which run first).

It would be very useful if we could get a breakdown of how long the following take:

- The unit tests (repo dependent - slowest in the runtime due to the number and complexity I suspect).

- Each of the functional and integration test categories:

  https://github.com/kata-containers/tests/blob/master/Makefile#L11..L13

Also, it would be interesting to debate the relative importance of each test category so we can come up with some sort of optimal ordering / grouping along with the approximate timing of each.

**Comment by jodh-intel** [comment]
... And since I'm the cause of some of it:

- We really need to find a way to allow the CI (specifically probably https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh) to somehow mark a CI run as "done" if it only changes docs.
- Ideally, we'd also allow a github force-merge if the PR is "do only" too but that might be harder I suspect.

In summary, there's no point chewing CPU time on thousands of tests for a PR that fixes a typo ;)

**Comment by chavafg** [comment]
Hi, 
Thanks for the suggestions... I agree that the sniff test idea would be useful. 
We know that travis do this kind of testing (unit tests + static checks), it may be a good idea to only run jenkins jobs if travis has already passed. Not sure if from jenkins we can check the status of travis, but will investigate. Also agree about skipping (or running minimal checks) the CI when only docs are modified.

I'll open another issue to track these suggestions. 

@grahamwhaley about the master job for the s390 arch in the tests repo, @GabyCT created it to verify if the job was stable enough to add the job to more repos.

**Comment by jodh-intel** [comment]
Yeah, Travis is an interesting one. We have tried to [remove it](https://github.com/kata-containers/kata-containers/issues/22) as its use seemed redundant now we have Jenkins on systems that support virtualisation.

**But**, Travis is very fast so might suffice for the "sniff test".

There *may* be some unit tests that need virtualisation support, but we could always add a new [Test Constraint to allow those to be skipped if the host doesn't support them](https://github.com/kata-containers/runtime/tree/master/pkg/katatestutils#test-constraints). That would be fine as they would only get skipped for the sniff test - when we run the "real" tests under Jenkins, we would have virtualisation support so all tests would eventually get run.

**Comment by grahamwhaley** [comment]
@chavafg @Pennyzct - is this issue solved now?

**Comment by chavafg** [comment]
I think so, we now have 2 nodes available and I haven't seen jobs queued for long... Closing.
