### ISSUE TITLE
kata 2.0:  move ci repo to tests?

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/ci#260]
**Which feature do you think can be improved?**

At part of repo consolidation process during kata 2.0 phrase, should we merge ci with tests as well? They serve similar purpose and do not really need to be seperated.

**How can it be improved?**

Move this repo inside the tests repo.

**Comment by jodh-intel** [comment]
I think it makes sense to combine CI + tests. But, does it make sense to move both to https://github.com/kata-containers rather than moving CI -> tests I wonder?

Current dump of what I was imagining we might do (but needs discussion and pros/cons identified for all...)

| Repo | Move to `kata-containers`?  | Notes |
|-|-|-|
| `agent` | no | Not necessary - archive this repo eventually as we won't need it due to the new rust agent |
| `ci` | yes? |
| `community` | no | By keeping it as a separate repo, we can allow different privilege levels |
| `documentation` | yes? | To some degree depends how big this might get (think big image files, etc)
| `ksm-throttler` | yes? | Is this component still providing value to users I wonder? |
| `osbuilder` | no? | Can't decide if this should be moved or kept stand-alone |
| `packaging` | yes |
| `proxy` | yes | |
| `runtime` | yes | |
| `shim` | yes | |
| `tests` | yes? | I was originally thinking this should be kept stand-alone, but it would simplify matters if it was moved into `kata-containers` |

I think we could use a  GitHub project to track the changes for these repo moves as part of Kata 2.0.

/cc @amshinde, @chavafg, @jcvenegas.

**Comment by chavafg** [comment]
+1 to merging `tests` and `CI` repos. I don't see any restriction right now to do this merge.

About moving both (merged) to `kata-containers` I also agree, but I think this should happen some time later? As the `tests` repo is being used by current CI for all other repos, I think it would be somehow complicated to update all jobs and repos with the new location. 

As soon as our needs for having kata 1.x.x releases decrease, we can think in doing the move as the impact would be lower, right?

**Comment by GabyCT** [comment]
Closing this issue as the above issue which is related has been closed
