### ISSUE TITLE
[RFC] - Consensus on Kata CI

### ISSUE THREAD

**Issue by egernst** [kata-containers/ci#4]
# Kata Containers CI

## Background - existing working solution from Clear Containers:
On Clear Containers we had a couple of iterations on creating a CI system and found that using Jenkins and 'slave nodes' on Azure, leveraging nested virtualization, gave us the most external visibility and flexibility.  Jenkins snapshot can be seen at [1] and actual Jenkins at [2].

Tests leveraged can be seen at [3].

[1] - https://github.com/clearcontainers/jenkins
[2] - http://cc-jenkins-ci.westus2.cloudapp.azure.com
[3] - https://github.com/clearcontainers/tests

## Current status for CI in Kata

As far as I can tell, we haven't had an explicit discussion on CI setup for Kata.  Currently, engineers on the Intel side have contributed many tests at [4], and this should already contain the existing test cases from runv and cc-runtime.  We have run our CI suite locally on Kata (does surprisingly well!) and we are looking to move forward to enable CI.

[4] - https://github.com/kata-containers/tests

## Recommended setup for CI

With the help of our architecture committee (thanks @jessfraz), we have credits in place to be able to setup our CI in Azure, mirroring what we have done already for Clear Containers, only %s/Clear/Kata, more or less.  I am of the opinion that this meets our needs very well and already has been proven in the Clear Container program and can be brought up very quickly.   Having said that, I want to make sure we get feedback on this so we can have consensus and move forward.

cc/ @sboeuf @chavafg @jessfraz @gnawux @jodh-intel @bergwolf @WeiZhang555 @sameo @tallclair  @laijs @GabyCT @grahamwhaley

**Comment by sboeuf** [comment]
:+1:

**Comment by jessfraz** [comment]
SGTM might as well use something that already works :)

**Comment by chavafg** [comment]
lgtm, this should let us have a working CI faster.

**Comment by gnawux** [comment]
looks good, the hyper team also runs a Jenkins with hyper.sh plugin, named [hykins][hykins], on hyper.sh

[hykins]:https://github.com/hyperhq/hykins

**Comment by jodh-intel** [comment]
+1 for Jenkins. Due to the number and variety of CI tests we have for Clear Containers, plus the fact we run the tests with full debug enabled, we really should try to setup the pipeline plugin:

- https://github.com/clearcontainers/jenkins/issues/7

That will require some script+config rework AIUI but would be worth the effort as it would allow us to identify which test or test group failed a lot more quickly.

**Comment by GabyCT** [comment]
lgtm

**Comment by egernst** [comment]
Thanks ya'll -- I'll look into setting up a Kata Specific account on azure today...

**Comment by egernst** [comment]
I created a new account, kata-containers@outlook.com, and applied the Azure pass as the subscription for this account.  I have created administrative accounts for both @sboeuf  and @chavafg (the domain name is _terrible_ ; sorry about that).

We shouldn't need many administrators for this account, but please let me know who else should be added here,  @gnawux et al

**Comment by jodh-intel** [comment]
Hi @egernst - it looks like you've started to setup Jenkins for some of the repos now. If so, could you self-assign this issue and use it to store the config in this repo?

**Comment by egernst** [comment]
@jodh-intel  --  I just setup the accounts -- @chavafg is working on the Jenkins configuration.  I'll assign to him.

**Comment by egernst** [comment]
@jodh-intel -- actually, should we just create a kata-containers/jenkins repo?  This may be a bit cleaner to store the configuration there (then on the node we can just do a git clone of just these bits).

**Comment by grahamwhaley** [comment]
@egernst debatable I think - we could, but if we then get more CIs (like one for metrics, or using a different framework), then we'd need one repo per instance.
The other option is we keep each instances' data in a subdir in this repo, and then you would clone/copy to the right place. Not quite as convenient - but, as there are a bunch of files under the Jenkins config tree that will not be getting put into the repos anyway (the secrets for a start), maybe it's not as bad as it sounds.

**Comment by egernst** [comment]
Yeah, this is a good point (don't want one repo per, etc).

**Comment by chavafg** [comment]
We can also add a directory called `jenkins` here.

**Comment by sboeuf** [comment]
Hi guys, if I used a separate repo, the reason was that it is easier for versioning the entire Jenkins server. But there was one drawback with this approach, we had to make sure to ignore a bunch of files.
I think we should go with one repo for every CI we could end up with, using different directories for each of them.
In case of Jenkins, this means we would modify the content of the `jenkins` folder, by updating manually all the xml files we need.

**Comment by emonty** [comment]
Hi! Sorry for the delay in commenting, just now was informed about this issue a short time ago.

I want to make sure you're all aware that as Kata is a part of the OpenStack Foundation you are MORE than welcome to use our existing CI infrastructure. In fact, we're excited to work with you on making Kata successful.

We do not have support for build nodes from Azure currently, but adding an Azure plugin would be pretty easy. https://review.openstack.org/#/c/535558 is a proposed AWS plugin - I'm betting an Azure plugin would be similary easy. Doing that would also open the door to Zuul users using Azure, which would be a great outcome of collaboration. That said, we have existing test node capacity on our set of OpenStack public clouds I'm sure we can make use of while working on and verifying the Azure plugin, so no need to block anything on that.

Zuul has full support for testing and optionally gating your github pull-requests. It also supports cross-repo dependencies which, given your repo organzation seems like a thing you could use. That same support will empower us to make integration testing jobs between Kata, OpenStack, and/or anything else where cross-repo integration testing might be useful such as Kubernetes. We're using the ability to cross-repo test Gerrit changes and GitHub pull requests to verify that the OpenStack modules in Ansible work with changes to OpenStack and the SDK libraries Ansible uses to talk to it.

Zuul is driven by self-testing in-repo job config, so although the Zuul itself is run by an existing team, the thing you care about (your jobs) would be under your control. That team is an open community-based team that you're all welcome to join, but doing so is in no way required for Kata to make use of Zuul. Zuul is also fully multi-tenant, so aspects of OpenStack testing that are expressions of OpenStack policy don't need to impact or affect Kata ... but jobs themselves can still be shared and re-used, so Kata-related jobs defined in Zuul can be used by OpenStack projects and vice-versa.

In fact, one of the primary designs of Zuul v3 is to facilitate what we call "3rd party CI" systems via directly-shareable job configs. I mention this because of the comment in the jenkins repo about how it could be used as a starting place by someone who wants a copy of the CI locally. With Zuul, people only need spin up a zuul and point it at your repos and all of the jobs you have will be live and continously updated in their instance. This is done to facilitate vendors doing local runs on hardware we can't possibly have copies of upstream but using the same jobs and reporting the results as advisory back upstream. It's a recent feature and we're still learning about the ins and outs of sharing jobs across systems via git in this manner, but that makes it a great time to get Kata involved.

Every job in Zuul currently gets one or more own single-use cloud VM with full sudo access. We're working on adding support for containers as build resources, which would be a great thing to collaborate with Kata on as we roll it out.

Our CI setup is also more than just Zuul. We index build logs in an ELK cluster, http://logstash.openstack.org/ - which allows our developers to analyze trends over time and identify niggly race-condition bugs that sneak past normal testing. We maintain a set of per-cloud-region mirrors that are designed for high-volume gate-testing needs (turns out a mirror having inconsistent state for a moment isn't a big deal for normal mirrors, but when you have thousands of test jobs running a momentary issue can have ripple effects) We have integration with a Zanata server https://translate.openstack.org to help drive internationalization. We have a host of other tools available to be used or not as makes sense. Some of them are rather strongly branded for the OpenStack project, but that can be addressed if we reach a point where there is a desire by Kata to make use of something but the OpenStack project branding is an issue.

I did a quick scan through the jobs you have in clearcontainers/jenkins. It doesn't seem like any of them would be hard to convert. I'd estimate a few hours of work or maybe a day.

As a path forward, the first step would be adding the OpenStack Zuul Github App https://github.com/apps/openstack-zuul to the https://github.com/kata-containers/ org (check 'all repositories'). We can then make a Kata tenant in Zuul and make sure you have an appropriate base setup and do some initial job migration. That way you can start to work towards having native Zuul content gradually with the Travis and Jenkins jobs in place. Once we're all happy with how things are working, then you can sunset Jenkins and Travis.

Most of us on the OpenStack Infra / Zuul side of things will be in Dublin for the OpenStack PTG week after next, so although I think getting basics in place could happen in very short order, it might be a couple of weeks before any of us would have bandwidth to help with any job content migration in earnest.

**Comment by egernst** [comment]
CI is up and running today with Jenkins/Azure.  

I'll close this now, as we'll stick with this until we get closer to having the project feature complete, at which point we'll reevaluate the various tools available to meet the Kata Containers CI needs.
